// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(CareersDbContext))]
    partial class CareersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Data.Models.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vacancies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("654a47b1-02f1-4382-9dda-6a14f436e9a4"),
                            Description = @"Holystone sutler line boatswain gangplank lad gibbet. Pink lanyard main sheet Plate Fleet rutters barque holystone. Case shot long clothes yard lugsail galleon dead men tell no tales to go on account. Keelhaul yo-ho-ho loot nipper list American Main fluke.
Pillage furl blow the man down pinnace chase guns fire in the hole hulk. Cog spike cutlass Jack Tar aye mizzenmast handsomely. Gun Gold Road walk the plank boom draft hang the jib tender. Boatswain bilge gally brigantine tack yardarm chandler.",
                            LocationId = 3,
                            ModifiedDate = new DateTime(2019, 12, 11, 20, 32, 37, 906, DateTimeKind.Utc).AddTicks(1940),
                            PostedDate = new DateTime(2019, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Alliances Operations Coordinator"
                        },
                        new
                        {
                            Id = new Guid("6de51672-fa28-4e51-aaee-637ec1fffc8d"),
                            Description = @"Provost topsail crimp square-rigged boatswain red ensign Chain Shot. Run a shot across the bow brig Plate Fleet lass marooned prow gunwalls. Jack Ketch long clothes lee dance the hempen jig rutters squiffy warp. Gun Spanish Main gangplank doubloon poop deck hogshead broadside.

Haul wind lee Shiver me timbers strike colors handsomely Nelsons folly rigging. Plate Fleet Barbary Coast hail-shot cable quarterdeck list Pieces of Eight. Bowsprit aye pinnace cog Letter of Marque galleon lad. Shiver me timbers code of conduct bilge water yo-ho-ho loaded to the gunwalls driver skysail.",
                            LocationId = 2,
                            ModifiedDate = new DateTime(2019, 12, 11, 20, 32, 37, 906, DateTimeKind.Utc).AddTicks(1940),
                            PostedDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Customer Service Manager"
                        },
                        new
                        {
                            Id = new Guid("b37743cd-4f07-475d-a4dc-a4ce7e6de1c1"),
                            Description = @"Provost Jack Tar Davy Jones' Locker snow topgallant lugsail mizzenmast. Maroon belay Sail ho grapple salmagundi rutters run a shot across the bow. Hulk clap of thunder line heave to Corsair pirate Jack Ketch. Cat o'nine tails no prey, no pay marooned carouser salmagundi squiffy Corsair.

Avast weigh anchor lugger execution dock mutiny run a shot across the bow chase guns. Deadlights coffer case shot stern gangway quarter interloper. Red ensign fluke gaff bucko skysail handsomely hempen halter. Topgallant starboard skysail hang the jib tender yawl coffer.",
                            LocationId = 2,
                            ModifiedDate = new DateTime(2019, 12, 11, 20, 32, 37, 906, DateTimeKind.Utc).AddTicks(1940),
                            PostedDate = new DateTime(2019, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Team Leader - Customer Care"
                        },
                        new
                        {
                            Id = new Guid("c7737c42-ef28-40c8-8bd1-7e2459ba959c"),
                            Description = @"Hands tack nipperkin fire ship man-of-war bilge water clap of thunder. Jib gangway jury mast parrel bowsprit Cat o'nine tails red ensign. Main sheet poop deck black jack rope's end pressgang Pieces of Eight lass. Black jack sloop chantey yard Sink me matey sheet.

American Main hands doubloon black spot knave broadside lanyard. Skysail gangplank black spot lookout pink clap of thunder yardarm. Sloop sheet careen trysail scuppers bucko black jack. Maroon ho pillage hearties jib overhaul doubloon.",
                            LocationId = 1,
                            ModifiedDate = new DateTime(2019, 12, 11, 20, 32, 37, 906, DateTimeKind.Utc).AddTicks(1940),
                            PostedDate = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Retail Centre Consultant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
